services:
  - type: web
    name: biblesnap-backend
    env: docker
    repo: https://github.com/mervalar/BibleSnap_v2
    branch: main
    rootDir: backend
    plan: free
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: <put the result of `php artisan key:generate --show` here>
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-d1a29uemcj7s73f3envg-a
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: biblesnap_db
      - key: DB_USERNAME
        value: biblesnap_db_user
      - key: DB_PASSWORD
        value: 3osr6cU7Rpoa6ei7lzMufC13lBHBWlCr
