services:
  - type: web
    name: biblesnap-backend
    env: php
    plan: free
    repo: https://github.com/mmervalar/BibleSnap_v2
    rootDir: backend
    buildCommand: |
      composer install --optimize-autoloader --no-dev
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
    startCommand: php artisan serve --host 0.0.0.0 --port $PORT
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: biblesnap-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: biblesnap-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: biblesnap-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: biblesnap-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: biblesnap-db
          property: password
