import { StyleSheet } from 'react-native';
import { COLORS } from '../theme';
import { getResponsiveDimensions } from '../bIbleStudyContent.styles';

const d = getResponsiveDimensions();

export default StyleSheet.create({
  chartCard: {
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    borderRadius: 16,
    padding: d.spacing.lg,
    marginBottom: d.spacing.lg,
  },
  chartHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: d.spacing.md,
  },
  chartTitle: {
    fontSize: d.fontSize.subtitle,
    fontWeight: '700',
    color: COLORS.text.primary,
  },
  chartStatsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: d.spacing.xs,
    gap: d.spacing.md,
    flexWrap: 'wrap',
  },
  chartStatItem: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  chartStatText: {
    fontSize: d.fontSize.caption,
    color: COLORS.text.secondary,
    fontWeight: '500',
  },
  chartInsight: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(139, 93, 51, 0.1)',
    borderRadius: 12,
    padding: d.spacing.sm,
    marginTop: d.spacing.md,
    marginBottom: d.spacing.sm,
    borderLeftWidth: 3,
    borderLeftColor: COLORS.primary,
  },
  chartInsightExcellent: {
    backgroundColor: 'rgba(74, 119, 66, 0.15)',
    borderLeftColor: COLORS.semantic.success,
  },
  chartInsightGreat: {
    backgroundColor: 'rgba(139, 93, 51, 0.15)',
    borderLeftColor: COLORS.primary,
  },
  chartInsightGood: {
    backgroundColor: 'rgba(139, 93, 51, 0.1)',
    borderLeftColor: COLORS.primary,
  },
  chartInsightEncourage: {
    backgroundColor: 'rgba(244, 67, 54, 0.1)',
    borderLeftColor: COLORS.semantic.error,
  },
  chartInsightEmoji: { fontSize: 20, marginRight: d.spacing.xs },
  chartInsightText: {
    flex: 1,
    fontSize: d.fontSize.caption,
    color: COLORS.text.primary,
    fontWeight: '600',
    lineHeight: 16,
  },
  chartArea: { marginTop: d.spacing.md, marginBottom: d.spacing.sm },
  barChartContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
    height: 180,
    paddingHorizontal: d.spacing.xs,
    marginBottom: d.spacing.md,
  },
  barContainer: {
    flex: 1,
    alignItems: 'center',
    position: 'relative',
    marginHorizontal: 2,
  },
  barWrapper: {
    width: '100%',
    height: 150,
    justifyContent: 'flex-end',
    alignItems: 'center',
    position: 'relative',
  },
  bar: {
    width: '80%',
    minHeight: 4,
    backgroundColor: COLORS.border.light,
    borderRadius: 8,
    justifyContent: 'flex-end',
    alignItems: 'center',
    position: 'relative',
  },
  barFilled: {
    backgroundColor: COLORS.primary,
    shadowColor: COLORS.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 3,
  },
  barSelected: {
    backgroundColor: COLORS.accent,
    transform: [{ scaleX: 1.1 }],
    shadowOpacity: 0.5,
    shadowRadius: 6,
    elevation: 5,
  },
  barValue: {
    color: COLORS.background,
    fontSize: 11,
    fontWeight: '700',
    marginBottom: 2,
    textShadowColor: 'rgba(0, 0, 0, 0.3)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  averageIndicator: {
    position: 'absolute',
    left: 0,
    right: 0,
    height: 2,
    borderTopWidth: 1,
    borderTopColor: COLORS.text.secondary,
    borderTopStyle: 'dashed',
    opacity: 0.5,
  },
  barDayLabel: {
    fontSize: d.fontSize.caption,
    color: COLORS.text.secondary,
    marginTop: d.spacing.xs,
    fontWeight: '500',
  },
  barDayLabelActive: { fontWeight: '700', color: COLORS.primary },
  barDayLabelSelected: { color: COLORS.accent, fontSize: d.fontSize.caption + 1 },
  averageLineContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: d.spacing.sm,
    paddingTop: d.spacing.sm,
    borderTopWidth: 1,
    borderTopColor: COLORS.border.light,
  },
  averageLine: {
    flex: 1,
    height: 1,
    borderTopWidth: 1,
    borderTopColor: COLORS.text.secondary,
    borderStyle: 'dashed',
    marginRight: d.spacing.sm,
    opacity: 0.5,
  },
  averageLineLabel: {
    fontSize: d.fontSize.caption,
    color: COLORS.text.secondary,
    fontWeight: '600',
  },
  chartLegend: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: d.spacing.md,
    marginTop: d.spacing.sm,
    flexWrap: 'wrap',
  },
  legendItem: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  legendDot: { width: 12, height: 12, borderRadius: 6 },
  legendDotDashed: {
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderStyle: 'dashed',
  },
  legendText: {
    fontSize: d.fontSize.caption,
    color: COLORS.text.secondary,
    fontWeight: '500',
  },
});
