// filepath: /home/merveille/projetPerso/BibleSnap_v2/frontend/styles/bIbleStudyContent.styles.js
import { StyleSheet, Platform, Dimensions } from 'react-native';
import { COLORS } from './theme';

// Re-export COLORS so existing imports like
// `import { createStyles, COLORS } from '../styles/bIbleStudyContent.styles';`
// continue to work.
export { COLORS };

const { width: screenWidth } = Dimensions.get('window');

// Responsive dimensions helper
export const getResponsiveDimensions = () => {
  const isTablet = screenWidth >= 768;
  return {
    headerHeight: isTablet ? 80 : 60,
    cardPadding: isTablet ? 24 : 16,
    fontSize: {
      title: isTablet ? 24 : 20,
      subtitle: isTablet ? 18 : 16,
      body: isTablet ? 16 : 14,
      caption: isTablet ? 14 : 12,
    },
    spacing: {
      xs: 4,
      sm: 8,
      md: 16,
      lg: 24,
      xl: 32,
    },
    iconSize: {
      small: isTablet ? 20 : 16,
      medium: isTablet ? 24 : 20,
      large: isTablet ? 32 : 24,
    }
  };
};

export const createStyles = () => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.primary,
  },
  videoBackground: {
    ...StyleSheet.absoluteFillObject,
    zIndex: -1,
  },
  videoOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: COLORS.overlay,
    zIndex: 0,
  },
  loadingOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1000,
  },
  loadingContent: {
    backgroundColor: COLORS.background,
    padding: 32,
    borderRadius: 16,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 8,
  },
  loadingOverlayText: {
    marginTop: 16,
    color: COLORS.text.primary,
    fontWeight: '600',
  },
  header: {
    paddingHorizontal: 16,
    paddingTop: Platform.OS === 'ios' ? 10 : 30,
    paddingBottom: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  backButton: {
    width: 44,
    height: 44,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
    borderRadius: 22,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 5,
  },
  headerTitle: {
    fontWeight: '800',
    color: COLORS.text.light,
    letterSpacing: 0.5,
  },
  headerActionButton: {
    width: 44,
    height: 44,
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
    borderRadius: 22,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 5,
  },
  headerActionButtonActive: {
    backgroundColor: COLORS.primary,
  },
  searchContainer: {
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  searchInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
  },
  searchInput: {
    flex: 1,
    marginLeft: 8,
    color: COLORS.text.light,
  },
  clearSearchButton: {
    padding: 4,
  },
  filterBar: {
    flexDirection: 'row',
    paddingHorizontal: 16,
    paddingVertical: 8,
    gap: 10,
    justifyContent: 'space-between',
  },
  
  // Filter Button Styles (for modal buttons)
  filterButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
    flex: 1,
    minWidth: 0,
  },
  filterButtonText: {
    color: COLORS.text.light,
    fontSize: 12,
    fontWeight: '600',
    marginLeft: 6,
    flexShrink: 1,
  },

  // Dropdown styles (keep for backwards compatibility if needed)
  dropdownWrapper: {
    flex: 1,
    position: 'relative',
    zIndex: 100,
  },
  dropdownButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    gap: 8,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
  },
  dropdownButtonText: {
    flex: 1,
    color: COLORS.text.light,
    fontSize: 14,
    fontWeight: '600',
  },
  dropdownMenu: {
    position: 'absolute',
    top: 50,
    left: 0,
    right: 0,
    backgroundColor: 'rgba(255, 255, 255, 0.98)',
    borderRadius: 12,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
    maxHeight: 300,
  },
  dropdownItem: {
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border.light,
  },
  dropdownItemActive: {
    backgroundColor: COLORS.primary,
  },
  dropdownItemText: {
    fontSize: 14,
    fontWeight: '600',
    color: COLORS.text.primary,
  },
  dropdownItemTextActive: {
    color: '#FFF',
  },

  // Small Modal Styles (for replacing dropdowns)
  smallModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  smallModalContent: {
    backgroundColor: COLORS.background,
    borderRadius: 16,
    width: '85%',
    maxWidth: 320,
    maxHeight: '70%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 8,
  },
  smallModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    padding: 20,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border.light,
  },
  smallModalTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: COLORS.text.primary,
  },
  smallModalList: {
    maxHeight: 300,
  },
  smallModalItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 14,
    paddingHorizontal: 20,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border.light,
  },
  smallModalItemActive: {
    backgroundColor: COLORS.primary,
  },
  smallModalItemContent: {
    flex: 1,
  },
  smallModalItemText: {
    fontSize: 15,
    fontWeight: '600',
    color: COLORS.text.primary,
  },
  smallModalItemTextActive: {
    color: '#FFF',
  },
  smallModalItemSubtext: {
    fontSize: 12,
    color: COLORS.text.secondary,
    marginTop: 2,
  },
  smallModalItemSubtextActive: {
    color: 'rgba(255, 255, 255, 0.8)',
  },

  mainContent: {
    flex: 1,
  },
  content: {
    flex: 1,
  },
  planSummaryBottom: {
    marginHorizontal: 16,
    marginBottom: 50, // Increased to position higher above navbar
    padding: 12, // Reduced from 16 to make it shorter
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
    borderRadius: 14, // Slightly reduced
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
  },
  planSummaryContent: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8, // Reduced from 12
  },
  planInfoLeft: {
    flex: 1,
  },
  planTitle: {
    fontWeight: '700',
    color: COLORS.text.light,
    fontSize: 14, // Reduced from 16
    marginBottom: 2, // Reduced from 4
  },
  planSubtitle: {
    color: 'rgba(247, 240, 227, 0.8)',
    fontSize: 11, // Reduced from 12
  },
  planStatsRight: {
    alignItems: 'flex-end',
  },
  planPercentBadge: {
    backgroundColor: COLORS.primary,
    paddingHorizontal: 10, // Reduced from 12
    paddingVertical: 4, // Reduced from 6
    borderRadius: 10, // Reduced from 12
  },
  planPercentText: {
    fontWeight: '700',
    color: '#FFF',
    fontSize: 14, // Reduced from 16
  },
  planProgressBar: {
    height: 6, // Reduced from 8
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    borderRadius: 6, // Reduced from 8
    overflow: 'hidden',
  },
  planProgressFill: {
    height: '100%',
    backgroundColor: COLORS.primary,
    borderRadius: 6, // Reduced from 8 to match progress bar
  },
  gameMapWrap: {
    flex: 1,
  },
  journeyContainer: {
    paddingVertical: 20,
    paddingHorizontal: 20,
    paddingBottom: 20,
  },
  nodeWrapper: {
    alignItems: 'center',
    width: 150,
    position: 'relative',
    marginVertical: 0,
  },
  nodeTouchable: {
    alignItems: 'center',
    position: 'relative',
  },
  nodeExternalShadow: {
    position: 'absolute',
    width: 66,
    height: 66,
    borderRadius: 25,
    top: 10,
    left: 36,
    opacity: 0.25,
    zIndex: -1,
  },
  currentNodeRing: {
    position: 'absolute',
    width: 90,
    height: 90,
    borderRadius: 45,
    borderWidth: 3,
    top: -10,
    opacity: 0.3,
    zIndex: 0,
  },
  nodeCircle: {
    width: 70,
    height: 70,
    borderRadius: 35,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
    overflow: 'hidden',
  },
  nodeInnerShadow: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: '30%',
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    borderTopLeftRadius: 35,
    borderTopRightRadius: 35,
    zIndex: 1,
  },
  nodeLabelContainer: {
    marginTop: 16,
    alignItems: 'center',
    width: 140,
  },
  nodeLabel: {
    fontSize: 15,
    fontWeight: '700',
    textAlign: 'center',
    marginBottom: 4,
  },
  nodeSubtitle: {
    fontSize: 12,
    textAlign: 'center',
    lineHeight: 16,
  },
  emptyContainer: {
    padding: 60,
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyTitle: {
    fontWeight: '700',
    color: COLORS.text.light,
    marginTop: 16,
    marginBottom: 8,
    textAlign: 'center',
  },
  emptyText: {
    color: 'rgba(247, 240, 227, 0.8)',
    textAlign: 'center',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  modalContent: {
    backgroundColor: COLORS.background,
    borderRadius: 20,
    padding: 24,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.3,
    shadowRadius: 20,
    elevation: 10,
    width: '90%',
    maxWidth: 400,
  },
  modalTitle: {
    fontSize: 22,
    fontWeight: '800',
    color: COLORS.text.primary,
    marginBottom: 8,
    textAlign: 'center',
  },
  modalSubtitle: {
    color: COLORS.text.secondary,
    marginBottom: 24,
    textAlign: 'center',
    fontSize: 14,
  },
  modalLabel: {
    color: COLORS.text.secondary,
    marginBottom: 8,
    fontSize: 14,
    fontWeight: '600',
  },
  dateButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    padding: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: COLORS.border.light,
    backgroundColor: COLORS.surface,
  },
  dateButtonText: {
    color: COLORS.text.primary,
    fontWeight: '600',
  },
  planOption: {
    width: '100%',
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 10,
    backgroundColor: COLORS.surface,
    marginBottom: 8,
    borderWidth: 2,
    borderColor: COLORS.border.light,
  },
  planOptionActive: {
    backgroundColor: COLORS.primary,
    borderColor: COLORS.primary,
  },
  planOptionContent: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
  },
  planOptionText: {
    color: COLORS.text.primary,
    fontWeight: '700',
    fontSize: 14,
  },
  planOptionTextActive: {
    color: '#FFF',
  },
  planOptionSubtext: {
    color: COLORS.text.secondary,
    fontSize: 11,
    marginTop: 0,
  },
  planOptionSubtextActive: {
    color: '#FFF',
    opacity: 0.9,
  },
  unlockInfo: {
    backgroundColor: COLORS.surface,
    padding: 16,
    borderRadius: 12,
    marginVertical: 16,
    width: '100%',
  },
  unlockLabel: {
    color: COLORS.text.secondary,
    fontSize: 12,
    marginBottom: 4,
    fontWeight: '600',
  },
  unlockValue: {
    color: COLORS.text.primary,
    fontWeight: '700',
    fontSize: 15,
  },
  modalActions: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 20,
    width: '100%',
  },
  modalButton: {
    flex: 1,
    padding: 14,
    borderRadius: 12,
    backgroundColor: COLORS.surface,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: COLORS.border.light,
  },
  modalButtonPrimary: {
    backgroundColor: COLORS.primary,
    borderColor: COLORS.primary,
  },
  modalButtonText: {
    color: COLORS.text.primary,
    fontWeight: '700',
  },
  modalButtonPrimaryText: {
    color: '#FFF',
    fontWeight: '700',
  },
  modalCloseButton: {
    marginTop: 16,
    alignSelf: 'center',
    padding: 10,
  },
  modalCloseText: {
    color: COLORS.text.secondary,
    fontWeight: '600',
  },
  lessonsPerDaySeparator: {
    marginVertical: 20,
    paddingHorizontal: 16,
    alignItems: 'center',
  },
  separatorLine: {
    height: 1,
    width: '100%',
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    marginVertical: 8,
  },
  lessonsPerDayContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingVertical: 8,
    paddingHorizontal: 16,
    backgroundColor: 'rgba(74, 103, 65, 0.2)', // accent color with opacity
    borderRadius: 20,
    borderWidth: 1,
    borderColor: 'rgba(74, 103, 65, 0.4)',
  },
  lessonsPerDayText: {
    color: COLORS.text.light,
    fontSize: 14,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  encouragementBanner: {
    position: 'absolute',
    top: Platform.OS === 'ios' ? 50 : 40,
    left: 16,
    right: 16,
    flexDirection: 'row',
    alignItems: 'center',
    padding: 12,
    borderRadius: 12,
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    zIndex: 1000,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 10,
  },
  encouragementBannerSad: {
    backgroundColor: 'rgba(255, 235, 235, 0.95)',
    borderLeftWidth: 4,
    borderLeftColor: COLORS.semantic.error,
  },
  encouragementBannerHappy: {
    backgroundColor: 'rgba(235, 255, 235, 0.95)',
    borderLeftWidth: 4,
    borderLeftColor: COLORS.semantic.success,
  },
  encouragementEmoji: {
    fontSize: 24,
    marginRight: 12,
  },
  encouragementText: {
    flex: 1,
    fontSize: 14,
    fontWeight: '600',
    color: COLORS.text.primary,
  },
  encouragementClose: {
    padding: 4,
  },
  aheadPopupOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  aheadPopupContent: {
    backgroundColor: COLORS.background,
    borderRadius: 20,
    padding: 24,
    alignItems: 'center',
    maxWidth: 300,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 15,
  },
  aheadPopupEmoji: {
    fontSize: 48,
    marginBottom: 12,
  },
  aheadPopupTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: COLORS.text.primary,
    marginBottom: 8,
  },
  aheadPopupText: {
    fontSize: 14,
    color: COLORS.text.secondary,
    textAlign: 'center',
    marginBottom: 20,
    lineHeight: 20,
  },
  aheadPopupButton: {
    backgroundColor: COLORS.primary,
    paddingVertical: 12,
    paddingHorizontal: 32,
    borderRadius: 25,
    minWidth: 120,
  },
  aheadPopupButtonText: {
    color: COLORS.text.light,
    fontSize: 16,
    fontWeight: '700',
    textAlign: 'center',
  },
  // Filter Modal Styles - Professional & Thin
  filterModalHeader: {
    alignItems: 'center',
    marginBottom: 12,
  },
  filterExplanation: {
    fontSize: 12,
    color: COLORS.text.secondary,
    textAlign: 'center',
    marginTop: 6,
    fontStyle: 'italic',
    lineHeight: 16,
    paddingHorizontal: 8,
  },
  filterCardsContainer: {
    width: '100%',
    gap: 8,
    marginBottom: 6,
  },
  filterCardWrapper: {
    position: 'relative',
    marginBottom: 6,
    overflow: 'visible',
  },
  filterCard: {
    backgroundColor: COLORS.surface,
    borderRadius: 12,
    padding: 12,
    borderWidth: 1.5,
    borderColor: COLORS.border.light,
    minHeight: 65,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 3,
    elevation: 2,
  },
  filterCardActive: {
    backgroundColor: COLORS.primary,
    borderColor: COLORS.primary,
    shadowColor: COLORS.primary,
    shadowOpacity: 0.25,
    shadowRadius: 6,
    elevation: 5,
  },
  filterCardPickupBook: {
    paddingLeft: 48,
  },
  filterCardHistorical: {
    paddingRight: 48,
  },
  filterCardImageTopRight: {
    position: 'absolute',
    top: -6,
    right: -6,
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: 'rgba(139, 93, 51, 0.12)',
    justifyContent: 'center',
    alignItems: 'center',
    transform: [{ rotate: '12deg' }],
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.12,
    shadowRadius: 3,
    elevation: 3,
  },
  filterCardImageTopRightActive: {
    backgroundColor: 'rgba(255, 255, 255, 0.3)',
    transform: [{ rotate: '12deg' }, { scale: 1.08 }],
  },
  filterCardImageBehind: {
    position: 'absolute',
    left: -18,
    top: '50%',
    transform: [{ translateY: -22 }, { rotate: '-10deg' }],
    width: 52,
    height: 52,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 0,
    opacity: 0.35,
  },
  filterCardImageBehindActive: {
    opacity: 0.65,
    transform: [{ translateY: -22 }, { rotate: '-10deg' }, { scale: 1.12 }],
  },
  filterCardImageBehindRight: {
    position: 'absolute',
    right: -18,
    top: '50%',
    transform: [{ translateY: -22 }, { rotate: '10deg' }],
    width: 52,
    height: 52,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 0,
    opacity: 0.35,
  },
  filterCardImageBehindRightActive: {
    opacity: 0.65,
    transform: [{ translateY: -22 }, { rotate: '10deg' }, { scale: 1.12 }],
  },
  filterCardContent: {
    zIndex: 1,
    position: 'relative',
  },
  filterCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 3,
  },
  filterCardTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: COLORS.text.primary,
    flex: 1,
    letterSpacing: 0.2,
  },
  filterCardTitleActive: {
    color: '#FFFFFF',
  },
  filterCardDescription: {
    fontSize: 11,
    color: COLORS.text.secondary,
    fontStyle: 'italic',
    lineHeight: 15,
    marginTop: 1,
  },
  filterCardDescriptionActive: {
    color: 'rgba(255, 255, 255, 0.85)',
  },
  // Unlock Modal Styles
  unlockModalContent: {
    backgroundColor: COLORS.background,
    borderRadius: 12,
    padding: 16,
    alignItems: 'center',
    maxWidth: 260,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 10,
  },
  unlockModalTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: COLORS.text.primary,
    marginBottom: 4,
    textAlign: 'center',
  },
  unlockModalSubtitle: {
    fontSize: 12,
    color: COLORS.text.secondary,
    textAlign: 'center',
    lineHeight: 16,
  },
  unlockModalButton: {
    marginTop: 12,
    paddingVertical: 8,
    paddingHorizontal: 20,
    borderRadius: 8,
    backgroundColor: COLORS.primary,
  },
  unlockModalButtonText: {
    color: '#FFFFFF',
    fontWeight: '600',
    fontSize: 13,
  },
  // BibleStudyContent specific styles
  headerButtons: {
    position: 'absolute',
    top: Platform.OS === 'ios' ? 50 : 40,
    right: 16,
    zIndex: 100,
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
  },
  closeButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 5,
  },
  contentContainer: {
    padding: 24,
    paddingTop: Platform.OS === 'ios' ? 60 : 50,
    paddingBottom: 64,
  },
  titleSection: {
    alignItems: 'center',
    marginBottom: 32,
  },
  mainTitle: {
    fontSize: 28,
    fontWeight: '800',
    color: COLORS.text.light,
    marginBottom: 8,
    letterSpacing: 1,
  },
  dayLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: COLORS.text.light,
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
    paddingHorizontal: 16,
    paddingVertical: 4,
    borderRadius: 20,
  },
  descriptionCard: {
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    borderRadius: 16,
    padding: 24,
    marginBottom: 24,
  },
  cardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
  },
  cardHeaderText: {
    fontSize: 18,
    fontWeight: '700',
    color: COLORS.text.primary,
    marginLeft: 8,
  },
  descriptionText: {
    fontSize: 16,
    color: COLORS.text.secondary,
    lineHeight: 24,
  },
  readingCard: {
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    borderRadius: 16,
    padding: 24,
    marginBottom: 32,
  },
  readingHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border.light,
  },
  readingTitleContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  readingTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: COLORS.text.primary,
    marginLeft: 8,
  },
  checkbox: {
    width: 24,
    height: 24,
    borderRadius: 6,
    borderWidth: 2,
    borderColor: COLORS.border.medium,
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkboxChecked: {
    backgroundColor: COLORS.semantic.success,
    borderColor: COLORS.semantic.success,
  },
  bookToRead: {
    marginBottom: 24,
  },
  bookItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: COLORS.surface,
    padding: 16,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: COLORS.border.light,
  },
  bookInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    gap: 8,
  },
  bookText: {
    fontSize: 16,
    fontWeight: '600',
    color: COLORS.text.primary,
    flex: 1,
  },
  upcomingSection: {
    marginTop: 8,
  },
  upcomingSectionTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: COLORS.text.light,
    marginBottom: 16,
  },
  upcomingCard: {
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
  },
  upcomingContent: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
  },
  upcomingIcon: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 16,
  },
  upcomingInfo: {
    flex: 1,
  },
  upcomingDay: {
    fontSize: 12,
    fontWeight: '600',
    color: COLORS.text.light,
    marginBottom: 4,
  },
  upcomingTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: COLORS.text.light,
  },
  noteButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.accent,
    paddingVertical: 16,
    paddingHorizontal: 24,
    borderRadius: 12,
    marginTop: 24,
    gap: 8,
  },
  noteButtonText: {
    fontSize: 16,
    fontWeight: '700',
    color: COLORS.background,
  },
  celebrationOverlay: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 9999,
  },
  confettiBubble: {
    position: 'absolute',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 5,
  },
  celebrationMessage: {
    backgroundColor: 'rgba(255, 255, 255, 0.98)',
    paddingHorizontal: 40,
    paddingVertical: 24,
    borderRadius: 20,
    alignItems: 'center',
  },
  celebrationIconCircle: {
    marginBottom: 12,
  },
  celebrationText: {
    fontSize: 24,
    fontWeight: '800',
    color: COLORS.text.primary,
    textAlign: 'center',
  },
  modalContainer: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  modalCloseButton: {
    position: 'absolute',
    top: Platform.OS === 'ios' ? 50 : 40,
    right: 16,
    zIndex: 9999,
  },
  modalCloseButtonInner: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: 'rgba(139, 93, 51, 0.9)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: '#FFFFFF',
  },
  // Share button
  shareButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: COLORS.primary,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 5,
    marginTop: 4,
  },
  // Shareable card styles - Matching the provided image design
  shareableCard: {
    width: 1080,
    height: 1080,
    overflow: 'hidden',
  },
  shareableTopSection: {
    flex: 2,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    paddingHorizontal: 80,
    paddingTop: 150,
    paddingBottom: 40,
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
  shareableContentWrapper: {
    width: '100%',
    marginTop: 120,
    alignItems: 'center',
  },
  shareableBottomSection: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    paddingHorizontal: 80,
    paddingTop: 40,
    paddingBottom: 40,
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  shareableHeader: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 0,
  },
  shareableDate: {
    fontSize: 32,
    fontWeight: '700',
    color: '#FFFFFF',
    opacity: 0.95,
  },
  shareableDay: {
    fontSize: 32,
    fontWeight: '700',
    color: '#FFFFFF',
    opacity: 0.95,
  },
 
 
  shareableDescription: {
    fontSize: 20,
    lineHeight: 30,
    color: '#FFFFFF',
    opacity: 0.9,
    textAlign: 'center',
    marginTop: 60,
    marginBottom: 40,
    paddingHorizontal: 20,
    fontStyle: 'italic',
  },
  shareableBooksToRead: {
    fontSize: 50,
    fontWeight: '600',
    color: '#FFFFFF',
    opacity: 0.9,
    textAlign: 'center',
    marginTop: 70,
    marginBottom: 50,
  },
  shareableVerseText: {
    fontSize: 36,
    lineHeight: 52,
    color: '#FFFFFF',
    textAlign: 'center',
    fontStyle: 'italic',
    fontWeight: '300',
    letterSpacing: 0.5,
    marginTop: 50,
    marginBottom: 40,
    paddingHorizontal: 20,
  },
  shareableDecorativeLine: {
    alignItems: 'center',
    marginBottom: 30,
  },
  shareableLine: {
    width: 150,
    height: 2,
    backgroundColor: '#FFFFFF',
    marginBottom: 10,
  },
  shareableDots: {
    flexDirection: 'row',
    gap: 8,
  },
  shareableDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#FFFFFF',
  },
  shareableReference: {
    fontSize: 22,
    fontWeight: '700',
    color: '#FFFFFF',
    textAlign: 'center',
    letterSpacing: 1,
  },
  shareableFooterText: {
    fontSize: 20,
    fontWeight: '700',
    color: '#FFFFFF',
    letterSpacing: 2,
    opacity: 0.9,
  },
});