import { StyleSheet, Platform, Dimensions } from 'react-native';
import { COLORS } from './bIbleStudyContent.styles';

const { height: H } = Dimensions.get('window');

export default StyleSheet.create({
  overlay: { flex: 1, justifyContent: 'flex-end' },
  backdrop: { ...StyleSheet.absoluteFillObject, backgroundColor: 'rgba(0,0,0,0.55)' },
  sheet: {
    backgroundColor: COLORS.background,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    maxHeight: H * 0.9,
    paddingHorizontal: 20,
    paddingBottom: Platform.OS === 'ios' ? 34 : 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.18,
    shadowRadius: 12,
    elevation: 16,
  },
  handle: {
    width: 40,
    height: 4,
    borderRadius: 2,
    backgroundColor: COLORS.border.light,
    alignSelf: 'center',
    marginTop: 10,
    marginBottom: 16,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 16,
  },
  headerLeft: { flex: 1 },
  bookTitle: { color: COLORS.text.primary, fontSize: 22, fontWeight: '800' },
  badgeRow: { flexDirection: 'row', gap: 6, marginTop: 5 },
  badge: {
    backgroundColor: COLORS.border.light,
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  badgeText: { color: COLORS.text.secondary, fontSize: 11, fontWeight: '600' },
  badgeGreen: { backgroundColor: 'rgba(74,103,65,0.1)' },
  badgeTextGreen: { color: COLORS.accent },
  closeBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: COLORS.border.light,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 12,
    marginTop: 2,
  },
  progressSection: { marginBottom: 20 },
  progressRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 7 },
  progressLabel: { color: COLORS.text.secondary, fontSize: 13 },
  progressPct: { color: COLORS.primary, fontSize: 13, fontWeight: '700' },
  track: { height: 6, backgroundColor: COLORS.border.light, borderRadius: 3 },
  fill: { height: 6, backgroundColor: COLORS.primary, borderRadius: 3 },
  scrollContent: { paddingBottom: 20 },
  section: { marginBottom: 24 },
  sectionLabel: { color: COLORS.text.primary, fontSize: 16, fontWeight: '700', marginBottom: 12 },
  chaptersHint: { color: COLORS.text.tertiary, fontSize: 12, marginBottom: 12 },
  grid: { flexDirection: 'row', flexWrap: 'wrap', gap: 7 },
  cell: {
    width: 44,
    height: 44,
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: COLORS.border.light,
    backgroundColor: COLORS.surface,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cellDone: {
    backgroundColor: 'rgba(74,119,66,0.18)',
    borderColor: COLORS.semantic.success,
    borderWidth: 2,
  },
  cellCheck: { position: 'absolute', top: 4, right: 4 },
  cellNum: { color: COLORS.text.tertiary, fontSize: 13, fontWeight: '600' },
  cellNumDone: { color: COLORS.semantic.success, fontWeight: '700' },
});
