import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: { 
    flex: 1, 
    backgroundColor: '#FAF9F7', // Warm off-white background
  },
  statusBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 16,
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    borderRadius: 12,
    marginBottom: 24,
    shadowColor: '#AE796D',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
  },
  statusTime: { 
    fontSize: 16, 
    fontWeight: '600', 
    color: '#5D4E37' // Dark brown for text
  },
  statusIcons: { flexDirection: 'row', alignItems: 'center' },
  signalContainer: { flexDirection: 'row', marginRight: 12 },
  signalDot: {
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: '#AE796D',
    marginRight: 4,
  },
  batteryContainer: {
    width: 24,
    height: 12,
    borderRadius: 6,
    borderWidth: 2,
    borderColor: '#AE796D',
    justifyContent: 'center',
    alignItems: 'center',
  },
  batteryLevel: {
    width: '80%',
    height: '80%',
    backgroundColor: '#A07553',
    borderRadius: 4,
  },
  // New gradient header container
  gradientHeader: {
    paddingTop: 40,
    paddingBottom: 40,
    paddingHorizontal: 24,
    marginHorizontal: -24, // Extend to container edges
    marginTop: -24, // Start from top
    borderBottomLeftRadius: 30,
    borderBottomRightRadius: 30,
    marginBottom: 20,
  },
  header: { 
    alignItems: 'center', 
    paddingTop: 20,
  },
  appIcon: {
    width: 100,
    height: 100,
    backgroundColor: '#fff',
    borderRadius: 30,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 20,
    shadowColor: 'rgba(0, 0, 0, 0.2)',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.25,
    shadowRadius: 16,
    elevation: 8,
  },
  appTitle: { 
    fontSize: 32, 
    fontWeight: '700', 
    color: '#5D4E37', 
    marginBottom: 8,
    letterSpacing: -0.5,
  },
  // New styles for text on gradient background
  appTitleOnGradient: { 
    fontSize: 32, 
    fontWeight: '700', 
    color: '#FFFFFF', 
    marginBottom: 8,
    letterSpacing: -0.5,
    textShadowColor: 'rgba(0, 0, 0, 0.2)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
  },
  appSubtitle: { 
    fontSize: 17, 
    color: '#8B7355',
    fontWeight: '500',
  },
  appSubtitleOnGradient: { 
    fontSize: 17, 
    color: 'rgba(255, 255, 255, 0.9)',
    fontWeight: '500',
    textShadowColor: 'rgba(0, 0, 0, 0.15)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  contentCard: {
    backgroundColor: '#fff',
    borderRadius: 28,
    padding: 28,
    paddingTop: 36,
    marginHorizontal: 24,
    marginTop: 10,
    shadowColor: '#AE796D',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.12,
    shadowRadius: 24,
    elevation: 12,
    borderWidth: 1,
    borderColor: 'rgba(174, 121, 109, 0.08)',
  },
  welcomeTitle: { 
    fontSize: 26, 
    fontWeight: '700', 
    color: '#5D4E37', 
    marginBottom: 12,
    textAlign: 'center',
  },
  welcomeText: { 
    fontSize: 17, 
    color: '#8B7355', 
    marginBottom: 32,
    textAlign: 'center',
    lineHeight: 24,
  },
  featureGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginBottom: 32,
  },
  featureItem: {
    width: '48%',
    backgroundColor: '#FEFDFB',
    borderRadius: 20,
    padding: 20,
    marginBottom: 16,
    shadowColor: '#AE796D',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 3,
    borderWidth: 1,
    borderColor: 'rgba(174, 121, 109, 0.12)',
  },
  featureIconContainer: {
    width: 48,
    height: 48,
    backgroundColor: '#AE796D',
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
    shadowColor: '#AE796D',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
  },
  featureTitle: { 
    fontSize: 17, 
    fontWeight: '600', 
    color: '#5D4E37', 
    marginBottom: 6 
  },
  featureDescription: { 
    fontSize: 14, 
    color: '#8B7355',
    lineHeight: 20,
  },
  reviewSection: { 
    marginBottom: 32,
    backgroundColor: '#FEFDFB',
    padding: 20,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: 'rgba(174, 121, 109, 0.12)',
  },
  ratingContainer: { 
    flexDirection: 'row', 
    marginBottom: 12,
    justifyContent: 'center',
  },
  reviewTextContainer: {
    alignItems: 'center',
  },
  reviewAuthor: { 
    fontSize: 18, 
    fontWeight: '600', 
    color: '#5D4E37',
    marginBottom: 8,
    textAlign: 'center',
  },
  reviewText: { 
    fontSize: 15, 
    color: '#8B7355', 
    textAlign: 'center',
    lineHeight: 22,
    fontStyle: 'italic',
  },
  buttonContainer: { 
    marginTop: 24,
    gap: 16,
  },
  primaryButton: {
    backgroundColor: '#AE796D',
    padding: 18,
    borderRadius: 16,
    shadowColor: '#AE796D',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.25,
    shadowRadius: 12,
    elevation: 8,
    transform: [{ scale: 1 }], // Initial scale for animation
  },
  primaryButtonPressed: {
    backgroundColor: '#A07553',
    transform: [{ scale: 0.96 }],
    shadowOpacity: 0.15,
    shadowOffset: { width: 0, height: 3 },
  },
  primaryButtonText: {
    color: '#fff',
    fontWeight: '700',
    textAlign: 'center',
    fontSize: 18,
    letterSpacing: 0.5,
  },
  secondaryButton: {
    backgroundColor: 'transparent',
    padding: 18,
    borderRadius: 16,
    borderWidth: 2,
    borderColor: '#AE796D',
    transform: [{ scale: 1 }],
  },
  secondaryButtonPressed: {
    backgroundColor: 'rgba(174, 121, 109, 0.08)',
    transform: [{ scale: 0.96 }],
  },
  secondaryButtonText: {
    color: '#AE796D',
    fontWeight: '600',
    textAlign: 'center',
    fontSize: 17,
    letterSpacing: 0.3,
  },
  termsText: {
    color: '#8B7355',
    fontSize: 13,
    textAlign: 'center',
    marginTop: 32,
    marginHorizontal: 24,
    lineHeight: 18,
  },
  linkText: {
    textDecorationLine: 'underline',
    color: '#AE796D',
    fontWeight: '500',
  },
});

export default styles;