import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#fff', padding: 24 },
  statusBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 16,
    backgroundColor: 'rgba(255, 255, 255, 0.8)',
    borderRadius: 12,
    marginBottom: 24,
  },
  statusTime: { fontSize: 16, fontWeight: '500', color: '#333' },
  statusIcons: { flexDirection: 'row', alignItems: 'center' },
  signalContainer: { flexDirection: 'row', marginRight: 12 },
  signalDot: {
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: '#333',
    marginRight: 4,
  },
  batteryContainer: {
    width: 24,
    height: 12,
    borderRadius: 6,
    borderWidth: 2,
    borderColor: '#333',
    justifyContent: 'center',
    alignItems: 'center',
  },
  batteryLevel: {
    width: '80%',
    height: '80%',
    backgroundColor: '#333',
    borderRadius: 6,
  },
  header: { alignItems: 'center', marginBottom: 32 },
  appIcon: {
    width: 80,
    height: 80,
    backgroundColor: '#fff',
    borderRadius: 40,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
  },
  appTitle: { fontSize: 28, fontWeight: 'bold', color: '#333', marginBottom: 8 },
  appSubtitle: { fontSize: 16, color: '#666' },
  contentCard: {
    backgroundColor: '#fff',
    borderRadius: 24,
    padding: 24,
    paddingTop: 32,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
  },
  welcomeTitle: { fontSize: 22, fontWeight: 'bold', color: '#333', marginBottom: 8 },
  welcomeText: { fontSize: 16, color: '#666', marginBottom: 24 },
  featureGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginBottom: 24,
  },
  featureItem: {
    width: '48%',
    backgroundColor: '#f9f9f9',
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  featureIconContainer: {
    width: 40,
    height: 40,
    backgroundColor: '#9333ea',
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
  },
  featureTitle: { fontSize: 16, fontWeight: '500', color: '#333', marginBottom: 4 },
  featureDescription: { fontSize: 14, color: '#666' },
  reviewSection: { marginBottom: 24 },
  ratingContainer: { flexDirection: 'row', marginBottom: 8 },
  reviewTextContainer: {},
  reviewAuthor: { fontSize: 16, fontWeight: '500', color: '#333' },
  reviewText: { fontSize: 14, color: '#666', marginTop: 4 },
  buttonContainer: { marginTop: 24 },
  primaryButton: {
    backgroundColor: '#9333ea',
    padding: 16,
    borderRadius: 12,
    marginBottom: 12,
  },
  primaryButtonText: {
    color: '#fff',
    fontWeight: 'bold',
    textAlign: 'center',
    fontSize: 18,
  },
  secondaryButtonText: {
    color: '#9333ea',
    fontWeight: 'bold',
    textAlign: 'center',
    fontSize: 18,
  },
  termsText: {
    color: '#6b7280',
    fontSize: 12,
    textAlign: 'center',
    marginTop: 24,
  },
  linkText: {
    textDecorationLine: 'underline',
  },
});

export default styles;